## Gradle Config
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Mod Data
mod_id=ponderous_planes
mod_name=Ponderous Planes
mod_license=MIT
mod_version=1.0.1
mod_group_id=net.vercte
mod_authors=Vercte
mod_description=ponder world for development

## First-Level Dependencies
minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)
neo_version=21.1.221
neo_version_range=[21,)
loader_version_range=[4,)